### ISSUE TITLE
Giving error related to addition tools

### ISSUE THREAD

**Issue by amrita1983** [bio-ontology-research-group/phenomenet-vp#6]
Hi,

was trying to run the tool with the command 
/bin/phenomenet-vp -f Swena_das_hardfiltered.vcf -p HP:0000821,HP:0000851,HP:0002925,HP:0005990,HP:0011791 -h -of 

but the error is showing the following

Missing dependencies required to run the tool. Please refer to the README file for more information.

I have tried to install that "pip install -r requirements.txt" package but its not working. Need help on this package installation is that a separate package or you have made any specific requirements.

**Comment by amrita1983** [comment]
after installing all the dependencies this error is coming

Mar 28, 2019 10:50:24 AM sa.edu.kaust.Main runTool
INFO: Initializing the model
Mar 28, 2019 10:50:26 AM sa.edu.kaust.Main runTool
SEVERE: java.nio.file.NoSuchFileException: data/omim_mode.txt
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at java.nio.file.Files.newBufferedReader(Files.java:2784)
        at java.nio.file.Files.newBufferedReader(Files.java:2816)
        at sa.edu.kaust.Main.loadInhModes(Main.java:148)
        at sa.edu.kaust.Main.runTool(Main.java:278)
        at sa.edu.kaust.Main.run(Main.java:225)
        at sa.edu.kaust.Main.main(Main.java:343)

even though I have that data/omim_mode.txt it is giving this error

**Comment by rozaimirazali** [comment]
> after installing all the dependencies this error is coming
> 
> Mar 28, 2019 10:50:24 AM sa.edu.kaust.Main runTool
> INFO: Initializing the model
> Mar 28, 2019 10:50:26 AM sa.edu.kaust.Main runTool
> SEVERE: java.nio.file.NoSuchFileException: data/omim_mode.txt
> at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
> at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
> at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
> at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
> at java.nio.file.Files.newByteChannel(Files.java:361)
> at java.nio.file.Files.newByteChannel(Files.java:407)
> at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
> at java.nio.file.Files.newInputStream(Files.java:152)
> at java.nio.file.Files.newBufferedReader(Files.java:2784)
> at java.nio.file.Files.newBufferedReader(Files.java:2816)
> at sa.edu.kaust.Main.loadInhModes(Main.java:148)
> at sa.edu.kaust.Main.runTool(Main.java:278)
> at sa.edu.kaust.Main.run(Main.java:225)
> at sa.edu.kaust.Main.main(Main.java:343)
> 
> even though I have that data/omim_mode.txt it is giving this error

Hi amrita1983,

Did you solve this issue? If not, the simplest way to solve this issue is by making a symlink of the location of the file to where you are running it.

For example, if your data folder is located in /software/phenomenet/phenomenet-vp-2.1/data/

and you are running the tool in /home/amrita1983/pvp

do 

ln -s /software/phenomenet/phenomenet-vp-2.1/data/ /home/amrita1983/pvp/
