### ISSUE TITLE
Get a OutOfMemoryError

### ISSUE THREAD

**Issue by qiangsir** [bio-ontology-research-group/phenomenet-vp#7]
Hi,

When I run the tool with command
bin/phenomenet-vp -f data/Miller.vcf -o OMIM:263750

I get this error the following

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.regex.Pattern.compile(Pattern.java:1688)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.replaceAll(String.java:2223)
	at sa.edu.kaust.Annotations.getAnnotations(Annotations.java:68)
	at sa.edu.kaust.Main.runTool(Main.java:302)
	at sa.edu.kaust.Main.run(Main.java:225)
	at sa.edu.kaust.Main.main(Main.java:343)

My computer has met the hardware requirements. I can't understand this error.

**Comment by rozaimirazali** [comment]
> Hi,
> 
> When I run the tool with command
> bin/phenomenet-vp -f data/Miller.vcf -o OMIM:263750
> 
> I get this error the following
> 
> Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
> at java.util.regex.Pattern.compile(Pattern.java:1688)
> at java.util.regex.Pattern.(Pattern.java:1351)
> at java.util.regex.Pattern.compile(Pattern.java:1028)
> at java.lang.String.replaceAll(String.java:2223)
> at sa.edu.kaust.Annotations.getAnnotations(Annotations.java:68)
> at sa.edu.kaust.Main.runTool(Main.java:302)
> at sa.edu.kaust.Main.run(Main.java:225)
> at sa.edu.kaust.Main.main(Main.java:343)
> 
> My computer has met the hardware requirements. I can't understand this error.

I think this has something to do with your default Java heapsize. By default, the heapsize is 1/4 of the RAM.

Try to set the java heap size to something bigger.

example: in your .bash_profile add the following

export _JAVA_OPTIONS="-Xmx400g"
